---
title: "Geography and Mapping @ Stanford"
author: "cengel {sul-cidr}"
date: "May 22, 2015"
output: 
  html_document: 
    toc: yes
    toc_depth: 4
---
Courses taught during academic year 2014/2015  
From https://explorecourses.stanford.edu

## GIS

#### ANTHRO 98B/ANTHRO 298B/ARCHLGY 98B: Digital Methods in Archaeology

This is a course on digital technologies in archaeology used for documentation, visualization, and analysis of archaeological spaces and objects. Emphasizes hands-on approaches to image manipulation, virtual reality, GIS, CAD, and photogrammetry modeling methods.
Terms: Win | Units: 3-5 | UG Reqs: GER:DB-EngrAppSci | Grading: Letter or Credit/No Credit
Instructors: Rick, J. (PI)

#### ARCHLGY 125: Archaeologial Field Survey Methods
Practicum applying a variety of survey techniques to discover, map, and record archaeological sites. Basic cartographic skills for archaeologists and an introduction to GIS tools, GPS instruments, and geophysical techniques. Participants should be able to walk 3 - 4 miles over uneven terrain or make special arrangements with the instructor for transportation.
Terms: Spr | Units: 3 | Repeatable for credit | Grading: Letter or Credit/No Credit
Instructors: Jones, L. (PI)

#### EARTHSYS 144/EESS 164: Fundamentals of Geographic Information Science (GIS) 
Survey of geographic information including maps, satellite imagery, and census data, approaches to spatial data, and tools for integrating and examining spatially-explicit data. Emphasis is on fundamental concepts of geographic information science and associated technologies. Topics include geographic data structure, cartography, remotely sensed data, statistical analysis of geographic data, spatial analysis, map design, and geographic information system software. Computer lab assignments.
Terms: Aut | Units: 3-4 | UG Reqs: GER: DB-NatSci | Grading: Letter or Credit/No Credit
Instructors: Eichelberger, B. (PI) ; Thomas, N. (PI) ; Firme, R. (TA) ; Lin, H. (TA) 

#### EARTHSYS 181/EARTHSYS 281/EESS 181/EESS 281/URBANST 181: Urban Agriculture in the Developing World
In this advanced undergraduate course, students will learn about some of the key social and environmental challenges faced by cities in the developing world, and the current and potential role that urban agriculture plays in meeting (or exacerbating) those challenges. This is a service-learning course, and student teams will have the opportunity to partner with real partner organizations in a major developing world city to define and execute a project focused on urban development, and the current or potential role of urban agriculture. Service-learning projects will employ primarily the student's analytical skills such as synthesis of existing research findings, interdisciplinary experimental design, quantitative data analysis and visualization, GIS, and qualitative data collection through interviews and textual analysis. Previous coursework in the aforementioned analytical skills is preferred, but not required. Admission is by application.
Terms: Aut | Units: 3-4 | Grading: Letter or Credit/No Credit
Instructors: Gibbs-Plessl, T. (PI) ; Matson, P. (PI) ; Rymer, B. (TA)

#### HISTORY 401A: Spatial History: Concepts, Methods, Problems
Technical training in GIS, with modules taught by Stanford Spatial History Lab staff; conceptual work in the use of these techniques in spatial historical analysis. Students develop their own spatial history projects and produce beta versions of dynamic visualizations.
Terms: Spr | Units: 4-5 | Grading: Letter (ABCD/NP)
Instructors: Frank, Z. (PI)


## geography

#### AFRICAAM 158/FEMGEN 158: Black Queer Theory
This course takes a multifaceted approach to black queer theory, not only taking up black theories of gender and queer sexuality, but queer theoretical interrogations of blackness and race. The course will also examine some of the important ways that black queer theory reads and is intersected with issues like affect, epistemology, space and geography, power and subjectivity, religion, economy, the body, and the law, asking questions like: How have scholars critiqued the very language of queer and the ways it works as a signifier of white marginality? What are the different spaces we can find queer black relationality, eroticism, and kinship? How do we negotiate issues like trans*misogyny or tensions around gender and sexuality in the context of race? Throughout the course, students will become versed in foundational and emerging black queer theory as we engage scholars like Sharon Holland, Cathy Cohen, Hortense Spillers, Marlon B. Ross, Aliyyah Abdur-Rahman, Barbara Smith, Roderick Ferguson, Robert Reid-Pharr, E. Patrick Johnson, and many others. Students will also gain practice applying black queer theory as an interpretive lens for contemporary social issues and cultural production including film, music, art, and performance.
Terms: Win | Units: 5 | Grading: Letter or Credit/No Credit
Instructors: Caruthers, J. (PI)

#### AFRICAST 138B/ANTHRO 138B/URBANST 139: Urban Africa
This course explores the production of urban space and the social, cultural, and political significance of cities in sub-Saharan Africa. Topics include: architecture and the built environment; urban planning and colonial public health; migration and rural-urban dynamics; youth, politics, and popular culture; violence, policing, and the privatization of public space; (in)formality in housing, transportation, and employment; class, gender, and mobility in the public sphere; urban citizenship and `right to the city¿ movements; gentrification, tourism, and the commodification of poverty; and efforts to (re)theorize postcolonial African cities. Readings are drawn from anthropology, history, urban studies, and geography. Discussion will situate struggles over urban forms and the contours of everyday life within broader trends in the political economy of the region from the late colonial period to the present.
Terms: Spr | Units: 5 | Grading: Letter (ABCD/NP)
Instructors: West, A. (PI)

#### AMSTUD 124A/ARTHIST 152/ENGLISH 124/HISTORY 151/POLISCI 124A: The American West
The American West is characterized by frontier mythology, vast distances, marked aridity, and unique political and economic characteristics. This course integrates several disciplinary perspectives into a comprehensive examination of Western North America: its history, physical geography, climate, literature, art, film, institutions, politics, demography, economy, and continuing policy challenges. Students examine themes fundamental to understanding the region: time, space, water, peoples, and boom and bust cycles.
Terms: Spr | Units: 5 | UG Reqs: GER:DB-Hum, GER:EC-AmerCul, WAY-A-II, WAY-SI | Grading: Letter (ABCD/NP)
Instructors: Cain, B. (PI) ; Fishkin, S. (PI) ; Freyberg, D. (PI) ; Kennedy, D. (PI) ; Nemerov, A. (PI) fewer instructors for 

#### ANTHRO 42: Megacities
In this course we will examine the meaning, processes, and challenges of urbanization. Through a series of targeted readings across history and geography and through the study of varied means of representation (anthropology, literature, cartography, film, etc), the class will analyze the ways in which urban forms have come into being and created, met, and/or ignored challenges such as disease, water, transport, religious and class conflict, colonialism, labor, and trade. Students will read anthropology in conjunction with other disciplines (literature, urban planning, public health, architecture, and economics) to learn the ways in which ethnographies of immigration, urban poverty, class disparity, economic development and indicators, noise, and transportation substantively augment our understandings of how people live within globalization.
Terms: Win | Units: 5 | Grading: Letter (ABCD/NP)
Instructors: Jain, S. (PI)

#### ANTHRO 126/URBANST 114: Urban Culture in Global Perspective
Core course for Urban Studies majors. We will study urban space both historically and cross-culturally. Urban Studies, by definition, is an interdisciplinary field, where the methodological approaches draw upon a diverse set of analytic tools. Disciplines that occupy a prominent place in this class are geography, cultural anthropology, sociology, history, media studies, and literature. In this context, we will discuss the importance of cities around the world to the economic, cultural, and political well-being of modern societies and examine how forces such as industrialization, decentralization, and globalization affect the structure and function of cities.
Terms: Aut | Units: 5 | UG Reqs: GER:DB-SocSci, WAY-ED, WAY-SI | Grading: Letter (ABCD/NP)
Instructors: Hansen, T. (PI)

#### ANTHRO 141B: The Anthropology of Bits and Bytes: Digital Media in the Developing World
Recent historical developments, including the widespread adoption of the mobile phone across Africa and Southeast Asia, the ¿Arab Spring,¿ and the rise of technology sectors in cities such as Nairobi, Bangalore, and Accra, have turned digital technology in the ¿global South¿ into a topic of growing popular interest and increasing scholarly concern. This course attempts to make sense of these developments by interrogating diverse theoretical approaches to digital technology and assessing what these approaches reveal and obscure in specific cases of technology adoption in Africa, Asia, and Latin America. Students will be introduced to an overview of scholarly approaches to digital technology from anthropology, science and technology studies (STS), critical theory, geography, and communications studies. We will analyze the relative utility of these explanations through case studies of specific instances of technological production and/or use. These case studies will be drawn from both secondary texts and primary materials such as social media, digital maps, videos, blogs, and news reports. At the same time, we will examine how digital discourses and practices both draw upon and inform broader issues of context-specific political and cultural importance. Major topics to be discussed include ¿development¿ and the State, civil society and the ¿public sphere,¿ youth culture, gender politics, mobility, and globalization. Students will come away from the course with a strong understanding of the major issues at stake in the increasing digitalization of the ¿global South,¿ and the socio-cultural, political, and technical debates that frame them
Terms: Aut | Units: 5 | Grading: Letter (ABCD/NP)
Instructors: Poggiali, L. (PI)

#### ANTHRO 156B: Environment, Nature and Race
Environment, nature and race: Politics of belonging, exclusion, and embodiment. Scientific and popular understandings of race and ethnicity remain deeply entangled with ideas about "nature" and the "environment". This course will introduce students to some of the many ways that nature, environment, and race have been and remain intertwined, for better or for worse. What does it mean to claim race is "natural"? To what extent is race shaped by environment and vice versa? How are the politics of race linked to the politics of environmentalism? The class will begin with a brief treatment of current critical consensus on the biology of race and the cultural politics of race and nature, and move on to a theoretical discussion of how humans and "nature" interact. From there, the course moves into historical and ethnographic examples of the politics of race and the environment: the racialized and racializing character of particular environments; the ways that racial politics shape natural environments; and the politics of exclusion and belonging in environmental movements. Case studies will be both rural and urban and draw from anthropology, geography, history, and biology. The course will end by considering the recent resurgence of the race concept in biology.
Terms: Spr | Units: 3-5 | Grading: Letter or Credit/No Credit
Instructors: Gardiner, M. (PI)

#### ANTHRO 170/ANTHRO 270/EARTHSYS 172: Australian Ecosystems: Human Dimensions and Environmental Dynamics
This cross-disciplinary course surveys the history and prehistory of human ecological dynamics in Australia, drawing on geology, climatology, archaeology, geography, ecology and anthropology to understand the mutual dynamic relationships between the continent and its inhabitants. Topics include anthropogenic fire and fire ecology, animal extinctions, aridity and climate variability, colonization and spread of Homo sapiens, invasive species interactions, changes in human subsistence and mobility throughout the Pleistocene and Holocene as read through the archaeological record, the totemic geography and social organization of Aboriginal people at the time of European contact, the ecological and geographical aspects of the "Dreamtime", and contemporary issues of policy relative to Aboriginal land tenure and management.
Terms: Win | Units: 3 | UG Reqs: WAY-SI | Grading: Letter (ABCD/NP)
Instructors: Bird, R. (PI)

#### CSRE 156J/ANTHRO 156B: Environment, Nature and Race
Environment, nature and race: Politics of belonging, exclusion, and embodiment. Scientific and popular understandings of race and ethnicity remain deeply entangled with ideas about "nature" and the "environment". This course will introduce students to some of the many ways that nature, environment, and race have been and remain intertwined, for better or for worse. What does it mean to claim race is "natural"? To what extent is race shaped by environment and vice versa? How are the politics of race linked to the politics of environmentalism? The class will begin with a brief treatment of current critical consensus on the biology of race and the cultural politics of race and nature, and move on to a theoretical discussion of how humans and "nature" interact. From there, the course moves into historical and ethnographic examples of the politics of race and the environment: the racialized and racializing character of particular environments; the ways that racial politics shape natural environments; and the politics of exclusion and belonging in environmental movements. Case studies will be both rural and urban and draw from anthropology, geography, history, and biology. The course will end by considering the recent resurgence of the race concept in biology.
Terms: Spr | Units: 3-5 | Grading: Letter or Credit/No Credit
Instructors: Gardiner, M. (PI)

#### ECON 266: International Economics II
This course covers an introduction to models of international trade and economic geography from both a theoretical and an empirical perspective.
Terms: Win | Units: 2-5 | Grading: Letter or Credit/No Credit
Instructors: Donaldson, D. (PI)

#### ENGLISH 115A: Shakespeare and Modern Critical Developments
Approaches include gender studies and feminism, race studies, Shakespeare's geographies in relation to the field of cultural geography, and the importance of religion in the period.
Terms: Spr | Units: 5 | UG Reqs: GER:DB-Hum, WAY-A-II | Grading: Letter (ABCD/NP)
Instructors: Parker, P. (PI)

#### HISTORY 106A: Global Human Geography: Asia and Africa
Global patterns of demography, economic and social development, geopolitics, and cultural differentiation, covering E. Asia, S. Asia, S.E. Asia, Central Asia, N. Africa, and sub-Saharan Africa. Use of maps to depict geographical patterns and processes.
Terms: Spr | Units: 5 | UG Reqs: GER:DB-SocSci, GER:EC-GlobalCom, WAY-SI | Grading: Letter or Credit/No Credit
Instructors: Lewis, M. (PI) ; Levy, N. (TA)

#### HISTORY 106B: Global Human Geography: Europe and Americas
Patterns of demography, economic and social development, geopolitics, and cultural differentiation. Use of maps to depict geographical patterns and processes.
Terms: Aut | Units: 5 | UG Reqs: GER:DB-SocSci, GER:EC-GlobalCom, WAY-SI | Grading: Letter or Credit/No Credit
Instructors: Lewis, M. (PI) ; Dovern, L. (TA) ; Levy, N. (TA)

#### ITALIAN 129: Modern Italian Culture: Literary Landscapes
Italian national and cultural identity in the 19th and 20th centuries. Topics vary from year to year. In 2015, the course will address the importance of landscape, geography, and regional traditions and languages in modern Italian history and literature. Taught in Italian. Prerequisites: ITALLANG 22A or equivalent (2 years of Italian).
Terms: Spr | Units: 4 | UG Reqs: GER:DB-Hum, WAY-A-II | Grading: Letter or Credit/No Credit
Instructors: Pierson, I. (TA)

#### MED 229: Introduction to Global Health
Provides an overview of global health and how it is similar to and different from public health and tropical medicine. Topics include the evolution, economics, politics of global health, major players in global health, and issues of geography, politics, humanitarianism, human rights, science, research, culture and disease.
Terms: Spr | Units: 1 | Grading: Medical Option (Med-Ltr-CR/NC)

#### OSPBER 25: Architecture, Memory, Commemoration
Exploration of questions about architectural form together with a sense of place in Berlin and surrounding regional cities. Interdisciplinary approach to the study of urbanism and memory through the concerns of cultural geography, anthropology, history, fiction and films. Trips to sites to explore how memory is visualized in the built environment. Themes of the course include: "About Form," "Mapping the City," and "Heritage and Commemoration."
Terms: Aut | Units: 5 | UG Reqs: GER:DB-Hum | Grading: Letter (ABCD/NP)
Instructors: Ebron, P. (PI)


#### OSPBER 46: Gardens of Earthly Delight: Berlin's Culture of Landscape and Public Space
This course examines the cultural geography of Germany¿s social spaces as sites for the development of the personal, social, and political experiences of a German cultural identity. Focusing on literary forms, landscape art, and garden history in Berlin and its environs, we consider the roles of landscape and garden design and how they represent the cultural and social ideology of their times. Activities include readings and field trips. Additional writing for students who choose the 2 unit option.
Terms: Spr | Units: 1-2 | Grading: Satisfactory/No Credit
Instructors: Moya, P. (PI) ; Saldivar, R. (PI)


#### OSPFLOR 25: Italian Food: A Cultural History
Why is Italian cooking so popular? And why does it play such a key role in the national identity?nObserving a meal, we can explain everything, or almost, about people. Eating is a universal experience. However, not only we do not eat the same things but also the ways, places and times we eat change according to traditions and habits. The culture of food is deeply embedded in history.nThis course will use documentary sources as well as art, literature, cultural studies, statistical data, and movies to describe how meals can paint a fresco of the history of Italians and their food.nEconomy, culture, class, gender, race, geography, international relations: all have a part in depicting the outline of this history of Italian food in the last 150 years. And all raise questions: how can food mark social differences, set cultural boundaries, raise ethical and religious controversies, involve agribusiness and politics, question our own identities? A tasty travel to the very roots of our human sociality.
Terms: Spr | Units: 5 | UG Reqs: GER:DB-SocSci, GER:EC-GlobalCom, WAY-SI | Grading: Letter (ABCD/NP)
Instructors: Scarpellini, E. (PI)


#### OSPSANTG 58: Living Chile: A Land of Extremes
Physical, ecological, and human geography of Chile. Perceptions of the Chilean territory and technologies of study. Flora, fauna, and human adaptations to regional environments. Guest lectures; field trips; workshops.
Terms: Aut, Spr, Sum | Units: 5 | UG Reqs: GER:DB-EngrAppSci | Grading: Letter (ABCD/NP)

#### POLISCI 245R: Politics in Modern Iran
Modern Iran has been a smithy for political movements, ideologies, and types of states. Movements include nationalism, constitutionalism, Marxism, Islamic fundamentalism, social democracy, Islamic liberalism, and fascism. Forms of government include Oriental despotism, authoritarianism, Islamic theocracy, and liberal democracy. These varieties have appeared in Iran in an iteration shaped by history, geography, proximity to oil and the Soviet Union, and the hegemony of Islamic culture.
Terms: Win | Units: 5 | UG Reqs: GER:DB-SocSci, GER:EC-GlobalCom, WAY-SI | Grading: Letter or Credit/No Credit
Instructors: Milani, A. (PI)

## mapping

#### BIO 128/EARTHSYS 129: Geographic Impacts of Global Change: Mapping the Stories
Forces of global change (eg., climate disruption, biodiversity loss, disease) impart wide-ranging political, socioeconomic, and ecological impacts, creating an urgent need for science communication. Students will collect data for a region of the US using sources ranging from academic journals to popular media and create an interactive Story Map ( http://stanford.maps.arcgis.com/apps/StorytellingTextLegend/index.html?appid=dafe2393fd2e4acc8b0a4e6e71d0b6d5) that merges the scientific and human dimensions of global change. Students will interview stakeholders as part of a community-engaged learning experience and present the Map to national policy-makers. Our 2014 Map is being used by the CA Office of Planning & Research.
Terms: Spr | Units: 4 | Grading: Letter or Credit/No Credit
Instructors: Hadly, E. (PI) ; Mychajliw, A. (PI) ; Truebe, S. (PI)

#### CEE 32Q: Place: Making Space Now
This seminar argues that architeccts are ultimately "placemakers," and questions what that means in the contemporary world. Part I investigates the meaning of the word "place." Additional background for understanding contemporary place making will include a critique of the history of modern place-making through an examination of modern form. Part II examines two traditional notions of place by scale: from "home" to "the city." What elements give these conceptions of space a sense of place? To answer this question, themes such as memory, mapping, and boundary, among others, will be investigated. part III presents challenges to the traditional notions of place discussed in Part II. Topics addressed include: What does it mean to be "out of place"? What sense of place does a nomad have, and how is this represented? What are the "non-places" and how can architects design for these spaces? Part IV addresses the need to re-conceptualize contemporary space. The role of digital and cyber technologies, the construction of locality in a global world, and the in-between places that result from a world in flux are topics discussed in this section of the seminar. nLearning goals: Specific goals include clsoe reading of texts, understanding of philosophical thinking and writing, argument under uncertainty, and developed concepts of place, space and architecture.
Terms: Win | Units: 3 | UG Reqs: WAY-A-II | Grading: Letter or Credit/No Credit
Instructors: Barton, J. (PI) ; Beischer, T. (PI)

#### CEE 195/GES 111: Fundamentals of Structural Geology
Techniques for mapping using GPS and differential geometry to characterize structures; dimensional analysis and scaling relations; kinematics of deformation and flow; measurement and analysis of stress; elastic deformation and properties of rock; brittle deformation including fracture and faulting; linear viscous flow including folding and magma dynamics; model development and methodology. Models of tectonic processes are constructed and solutions visualized using MATLAB. Prerequisites: GES 1, MATH 51
Terms: Win | Units: 3 | UG Reqs: WAY-FR, WAY-SMA | Grading: Letter or Credit/No Credit
Instructors: Pollard, D. (PI)

#### CLASSICS 24N: What is a Map?
Exploration of the nature of maps via an overview of premodern mapping practices, combining theory and history of maps. Hands-on research involving Stanford's rare and historical maps, and chance to create own maps.
Terms: Win | Units: 4 | UG Reqs: WAY-A-II | Grading: Letter (ABCD/NP)
Instructors: Parker, G. (PI)

#### COMM 274D: Public Affairs Data Journalism II
Learn how to find, create and analyze data to tell news stories with public service impact. Uses relational databases, advanced queries, basic statistics, and mapping to analyze data for storytelling. Assignments may include stories, blog posts, and data visualizations, with at least one in-depth project based on data analysis. Prerequisites: COMM 273D or Journalism M.A. student.
Terms: Win | Units: 4 | Repeatable for credit | Grading: Letter or Credit/No Credit
Instructors: Phillips, C. (PI)

#### GES 105: Introduction to Field Methods
Two-week, field-based course in the White Mountains of eastern California. Introduction to the techniques for geologic mapping and geologic investigation in the field: systematic observations and data collection for lithologic columns and structural cross-sections. Interpretation of field relationships and data to determine the stratigraphic and deformational history of the region. Prerequisite: GES 1, recommended: GES 102.
Terms: Aut, Spr | Units: 3 | UG Reqs: WAY-SMA | Grading: Letter or Credit/No Credit
Instructors: Cina, S. (PI) ; Grove, M. (PI)

## spatial

#### ENERGY 160/ENERGY 260: Modeling Uncertainty in the Earth Sciences

Whether Earth Science modeling is performed on a local, regional or global scale, for scientific or engineering purposes, uncertainty is inherently present due to lack of data and lack of understanding of the underlying phenomena. This course highlights the various issues, techniques and practical modeling tools available for modeling uncertainty of complex 3D/4D Earth systems. The course focuses on a practical breath rather than theoretical depth. Topics covered are: the process of building models, sources of uncertainty, probabilistic techniques, spatial data analysis and geostatistics, grid and scale, spatio-temporal uncertainty, visualizing uncertainty in large dimensions, Monte Carlo simulation, reducing uncertainty with data, value of information. Applications to both local (reservoir, aquifer) and global (climate) are covered through literature study. Extensive software use with SGEMS and Petrel. Project homework. Prerequisites: algebra ( CME 104 or equivalent), introductory statistics course ( CME 106 or equivalent).
Terms: Win | Units: 3 | Grading: Letter (ABCD/NP)
Instructors: Caers, J. (PI) ; Haider, B. (TA)

#### ENERGY 240/GES 240: Geostatistics
Geostatistical theory and practical methodologies for quantifying and simulating spatial and spatio-temporal patterns for the Earth Sciences. Real case development of models of spatial continuity, including variograms, Boolean models and training images. Estimation versus simulation of spatial patterns. Loss functions. Estimation by kriging, co-kriging with secondary data. Dealing with data on various scales. Unconditional and conditional Boolean simulation, sequential simulation for continuous and categorical variables. Multi-variate geostatistical simulation. Probabilistic and pattern-based approaches to multiple-point simulation. Trend, secondary variable, auxiliary variable and probability-type constraints. Quality control techniques on generated models. Workflows for practical geostatistical applications in mining, petroleum, hydrogeology, remote sensing and environmental sciences. prerequisites: Energy 160/260 or basic course in data analysis/statistics
Terms: Spr | Units: 2-3 | Grading: Letter (ABCD/NP)
Instructors: Caers, J. (PI) ; Li, L. (TA)

#### EESS 214: Introduction to geostatistics and modeling of spatial uncertainty
Introduction of fundamental geostatistical tools for modeling spatial variability and uncertainty, and mapping of environmental attributes. Additional topics include sampling design and incorporation of different types of information (continuous, categorical) in prediction. Assignments consist of small problems to familiarize students with theoretical concepts, and applications dealing with the analysis and interpretation of various data sets (soil, water pollution, atmospheric constituents, remote sensing) primarily using Matlab. No prior programming experience is required. Open to graduates. Open to undergraduates with consent from the instructor. 3-credit option includes midterm/final or student-developed project. 4-credit option requires both. Prerequisite: College-level introductory statistics.
Terms: not given this year | Units: 3-4 | Grading: Letter (ABCD/NP)

GEOPHYS 241A/ENERGY 141/ENERGY 241: Seismic Reservoir Characterization 
(Same as GP241) Practical methods for quantitative characterization and uncertainty assessment of subsurface reservoir models integrating well-log and seismic data. Multidisciplinary combination of rock-physics, seismic attributes, sedimentological information and spatial statistical modeling techniques. Student teams build reservoir models using limited well data and seismic attributes typically available in practice, comparing alternative approaches. Software provided (SGEMS, Petrel, Matlab).nnRecommended: ERE240/260, or GP222/223, or GP260/262 or GES253/257; ERE246, GP112
Terms: Spr | Units: 3-4 | Grading: Letter (ABCD/NP)
Instructors: Mukerji, T. (PI)

#### HISTORY 205F: Digital History: Concepts, Methods, Problems
Students will study the development of the relationship between the discipline of history and computing tools through a combination of theoretical and hands-on activities, and readings. Students will read leading critical works, examine seminal digital projects, and examine the works of leading digital humanities scholars. The course will introduce students to concepts and methods within digital history, including text analysis, spatial history, data visualization, and digital scholarship. The end product of the course will be a born-digital scholarly product.
Terms: Aut | Units: 5 | Grading: Letter (ABCD/NP)
Instructors: Heppler, J. (PI)

####ME 215: From Maps to Meaning
One of the oldest visual tools created by humans to make sense of the complexities of our world, maps are unique in their ability to synthesize data, convey meaning through spatial logic, and deliver information at high resolution. They are also incredible tools for communication, data sorting, and insight finding. This is a hands-on, project-centered course where students will create maps to to synthesize complex information and also use maps as a tool for working on design problems. Students will tackle three main projects and several shorter assignments.
Terms: Win | Units: 3 | Grading: Satisfactory/No Credit
Instructors: Carter, C. (PI) ; Goel, A. (PI)

#### POLISCI 350D: Political Methodology IV: Advanced Topics
Covers advanced statistical tools that are useful for empirical research in political science. Possible topics include missing data, survey sampling and experimental designs for field research, machine learning, text mining, clustering, Bayesian methods, spatial statistics, and web scraping.
Terms: Spr | Units: 5 | Grading: Letter or Credit/No Credit
Instructors: Rivers, D. (PI)

#### STATS 253: Analysis of Spatial and Temporal Data
A unified treatment of methods for spatial data, time series, and other correlated data from the perspective of regression with correlated errors. Two main paradigms for dealing with autocorrelation: covariance modeling (kriging) and autoregressive processes. Bayesian methods. Prerequisites: applied linear algebra ( MATH 103 or equivalent), statistical estimation ( STATS 200 or CS 229), and linear regression ( STATS 203 or equivalent).
Terms: Sum | Units: 3 | Grading: Letter or Credit/No Credit
Instructors: Sun, D. (PI)

#### STATS 360/EESS 260: Advanced Statistical Methods for Earth System Analysis
Introduction for graduate students to important issues in data analysis relevant to earth system studies. Emphasis on methodology, concepts and implementation (in R), rather than formal proofs. Likely topics include the bootstrap, non-parametric methods, regression in the presence of spatial and temporal correlation, extreme value analysis, time-series analysis, high-dimensional regressions and change-point models. Topics subject to change each year. Prerequisites: STATS 110 or equivalent.
Terms: Win | Units: 3 | Grading: Letter or Credit/No Credit
Instructors: Rajaratnam, B. (PI)